---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allowed-deployment
  namespace: default
  labels:
    app: allowed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allowed
  template:
    metadata:
      labels:
        app: allowed
    spec:
      containers:
        - name: allowed
          # image: random.registry.io/nginx:1
          image: registry.docker.io/nginx:1
          ports:
            - containerPort: 80