---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: deployment-validation
webhooks:
  - name: "image-validation-controller.default.svc"
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "deployments" ]
        scope: "Namespaced"
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
        scope: "Namespaced"
    clientConfig:
      url: "https://image-validation-controller.default.svc/validate"
      # service:
      #   namespace: default
      #   name: image-validation-controller
      #   path: "/validate"
      #   port: 443
      caBundle: >
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsVENDQW4yZ0F3SUJBZ0lVSlpCZGJuRDlBdU1aL3BSQmxpUmd5RWRzVHJJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1B6RUxNQWtHQTFVRUJoTUNRVlV4TURBdUJnTlZCQU1NSjJsdFlXZGxMWFpoYkdsa1lYUnBiMjR0WTI5dQpkSEp2Ykd4bGNpNWtaV1poZFd4MExuTjJZekFlRncweU5UQTJNekF3TmpJeU1qVmFGdzB5TmpBMk16QXdOakl5Ck1qVmFNRDh4Q3pBSkJnTlZCQVlUQWtGVk1UQXdMZ1lEVlFRRERDZHBiV0ZuWlMxMllXeHBaR0YwYVc5dUxXTnYKYm5SeWIyeHNaWEl1WkdWbVlYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFDellSdGN1cHdmb2JvenFadyt3NkhCWjN2b2lVaWxWN0NVT1NmNEo5NWVIRlZvZ3ZZWXdTWEcxSWFuCmZRRXZoRU1JeXJoOStWZm1KSkdaMHVFMXNrQjRtczZ3bDRyL3V2b3ZTWUMxY1BhUkdSdDJhcXV5VW1qd1VmWnkKUXhuSzZHY2Mxd2lNZ3FucU9nbm1ieE1PQlFhbTg2cVo5NThJai90Q1JTR0RPVUZSQUIrcHFwdEFJWGNVZjdWMAoyTUh5Y2xma2lUMmt3M29XVmxMUVNRRHl2QzJ4V2J5S2RWVk5xNUQ3aGdFdUVscWNTSG1WaTF2eFlaYjVtUkZCCnBrc1FOeXNZaGw4YkNHRS9INWFJbC9IUWoxcEU5U20zd3RSYkJueDlmVnFzd3FFam1hNGluV1A4OTdTRzZGK0sKNzBJU0hMQnVBak4zdFp3MjdpOUFPUFdTMVFKbkFnTUJBQUdqZ1lnd2dZVXdIUVlEVlIwT0JCWUVGUERwQ3dxUQpVeklrSGY3YnJhS2lOblJmY0lIT01COEdBMVVkSXdRWU1CYUFGUERwQ3dxUVV6SWtIZjdicmFLaU5uUmZjSUhPCk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d01nWURWUjBSQkNzd0tZSW5hVzFoWjJVdGRtRnNhV1JoZEdsdmJpMWoKYjI1MGNtOXNiR1Z5TG1SbFptRjFiSFF1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUp1TUhoQmNxNwpvb0FwUTZWRkY1aEpXZHJRVmUyUTErekZYT2ViVTRsOWxBYW5WN1BpcEJqRll4RjhWQ2l5NHhKUGlMOTB2dnJsClRROWhCaVNEL2oxMnlDbnlRQ0ttUFdEM050NXBpSEt0eXR6bmRDeXFtSFNNdjFzK2d3ekk3WVB0YTlYdEJ0eU0KL2RPM1NmOERVVC96WWpaT2gwUWZNT1BkOUdoZCtGclpZSjJEdFlYTEZYSFlxUU4xcWp6NHFuWXIvaUdyMk9PbwpIRDkwUElSeXpYakxJNXZma0Y2UFdsQXpIQmtaTlpEZDBpT1ZieEZzRURPbHlGZWkyTGNGSzZyMFRLS1d0Qmh4Cjd3b3dCRTRxVmFBSHUrb1hoMWxXay9SVkdhQmpDTUJmKzZiRGdrUVY1YmY3MmJIaFREL09kbnhjTGFiWGdsYzIKeXZpL3EzVng4VWJNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5