apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-validation-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-validation-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-validation-controller
subjects:
- kind: ServiceAccount
  name: image-validation-controller
  namespace: default
