apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: registry.docker.io/nginx:latest
      ports:
        - containerPort: 80
